#!/bin/bash
# SSH-keygen wrapper script for git signing with Secretive
export SSH_AUTH_SOCK=/Users/francis/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
exec /usr/bin/ssh-keygen "$@"
